### ISSUE TITLE
unable to call lifecycle method [mount]" and if i change method [mount] on controlller,

### ISSUE THREAD

**Issue by study4you** [hbakouane/admin-user-chatting#7]
Please check this issue~
git clone~
composer update
cp .env.example .env
php artisan key:generate

and login~ displayed this error~
PHP8, latest Laravel version

**Comment by aliqadimi** [comment]
Hello, thank you for this repository,I have the same problem,I use your code in Laravel 7,This gives me an error when I enter the chat page
**** wire:poll="mount"****
Error here
Can you help me?

**Comment by hbakouane** [comment]
Solved in https://github.com/hbakouane/admin-user-chatting/commit/aa24677981fc094fd4db539b288b4555a0c05313
